### ISSUE TITLE
findSequencesOnDisk() now breaks with non-sequence files mixed in same directory

### ISSUE THREAD

**Issue by justinfx** [sqlboy/fileseq#25]
Reported by @matthewkapfhammer 

Reproduction:

```
test/
    file.json
    seq.0001.ext
    seq.0002.ext
```

```python
$ fileseq.findSequencesOnDisk("test")
ValueError: invalid literal for int() with base 10: ''
```

The problem is that because the DISK_RE pattern was recently updated, and there aren't adequate tests for `findSequencesOnDisk`, an unchecked frames list containing an empty string is being returned and tries to get converted into an int. Need to skip these cases in the loop.

**Comment by michaelmovies** [comment]
I've just pushed a branch with an additional test for these issues, as well as some proposed fixes.  The fixes do appear to solve the issue with findSequencesOnDisk, however looking into this exposed some knock-on effects from the earlier changes from #20 having not been applied to the findSequencesOnDisk and findSequenceOnDisk methods, as the "it's not a candidate for a frame number unless it either has an explicit placeholder or has a period in front of it" rule causes some issues with the existing tests for those two methods.

So this is a testing branch with some diff worth looking at and certainly discussing, but don't merge it.

**Comment by justinfx** [comment]
@michaelmovies , I did a pass at this in my own branch, and merged your unittest with my own, to check the results. In my version I seem to be able to preserve the existing behavior while addressing the fix. 

References
* Your branch:  [find_sequences_issue_25](https://github.com/sqlboy/fileseq/tree/find_sequences_issue_25)
* My branch:  [find_sequences_issue_25_justinfx](https://github.com/sqlboy/fileseq/tree/find_sequences_issue_25_justinfx)
* [Diff of our branches](https://github.com/sqlboy/fileseq/compare/find_sequences_issue_25...find_sequences_issue_25_justinfx)

Am I missing anything that you were addressing in your branch?

**Comment by michaelmovies** [comment]
@justinfx I've rebased from yours and added some new tests to show the issue, plus committed my fix back into my branch.

The main change is to fix an issue that caused findSequencesOnDisk to fail with a ValueError if a name had mixed dashes and numbers (ie /file4-4.exr).  That's existed since at least 0.5.1.

[current diff](https://github.com/sqlboy/fileseq/compare/find_sequences_issue_25_justinfx...find_sequences_issue_25?diff=unified&name=find_sequences_issue_25)
