### ISSUE TITLE
findSequencesOnDisk should not find hidden files by default

### ISSUE THREAD

**Issue by michaelmovies** [sqlboy/fileseq#27]
Recent changes to yield_sequences_in_list have started to expose hidden files missed by earlier versions of fileseq.  This changes the behavior of findSequencesOnDisk, however, which would not previously return hidden files, even if they existed in the directory being searched.  Showing hidden files seems appropriate as an optional behavior, specifically asked for, rather than the default one.

**Comment by justinfx** [comment]
Merged #28
