### ISSUE TITLE
Add TravisCI integration.

### ISSUE THREAD

**Issue by matthewkapfhammer** [sqlboy/fileseq#37]
- Add Travis yaml file.
- Lower verbosity setting.
- Add badge to README.

**Comment by justinfx** [comment]
Matt enabled Travis and I triggered a build. It's now passing!

**Comment by matthewkapfhammer** [comment]
Aww shucks... just in time for my birthday. :)

**Comment by justinfx** [comment]
Happy Birthday! You get a Travis report.
