### ISSUE TITLE
findSequenceOnDisk doesn't work on windows - regex needs to be updated to deal with backslashes

### ISSUE THREAD

**Issue by p0las** [sqlboy/fileseq#42]
here is updated regex for the DISK_PATTERN that fixes the issue on windows.
```
# Regular expression pattern for matching file names on disk.
DISK_PATTERN = r"^(.*[/\\])?(?:$|(.*?)(-?\d+)?(?:(\.[^.]*$)|$))"
DISK_RE = re.compile(DISK_PATTERN)
```
you use os.path.join that injects a backslash into the path (even if the original path has only forward slashes) and the regex chokes on it resulting in a wrong basename() which in turn breaks comparision in findSequenceOnDisk

this is never true on windows:
```
for match in matches:
    if match.basename() == basename and match.extension() == ext:
           return match
```

**Comment by justinfx** [comment]
Thanks for the report and the suggested fix to the regex. Did you want to submit this as a merge request, with a test, or are you just reporting the proposed regex?

**Comment by p0las** [comment]
I patched it on my end but I never tried to run the tests that come with fieseq so I decided to just post it as a comment/bug report. If/when I have a bit more time I can attempt to fix it properly and submit a pull request but it might be just easier for you to handle it as you are familiar with the code. I only started to use this library today and I don't want to mess it :-).

**Comment by justinfx** [comment]
Its ok that you only started using the library recently. We have code reviews on the merge requests to catch any issues. I am not a windows user so I had never run into this issue. But I can take your suggested code and work out a merge request for you to test and confirm, when I have a free moment.

**Comment by justinfx** [comment]
@p0las , can you give the `42_windows_path_sep` branch a test? I'm not a windows user and I needed to write a mock test that could emulate windows. It required a few more changes than what you found, so the test can still run on POSIX.

**Comment by p0las** [comment]
hi, I didn't check my email over the weekend. sorry. I was going to fix it but I'm glad I didn't start. currently the branch you mentioned fails on windows 10 with the following:
```
======================================================================
FAIL: testFormat (__main__.TestFileSequence)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run.py", line 1385, in testFormat
    self.assertEquals("step_seq/step1.1-13x4,14-17#.exr", str(seq))
AssertionError: 'step_seq/step1.1-13x4,14-17#.exr' != 'step_seq\\step1.1-13x4,14-17#.exr'

======================================================================
FAIL: testFindSequenceOnDisk (__main__.TestFindSequenceOnDisk)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run.py", line 1656, in testFindSequenceOnDisk
    self.assertEqual(actual, expected)
AssertionError: 'seq\\bar1000-1002,1004-1006#.exr' != 'seq/bar1000-1002,1004-1006#.exr'

======================================================================
FAIL: testFindSequenceOnDiskNegative (__main__.TestFindSequencesOnDisk)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run.py", line 1575, in testFindSequenceOnDiskNegative
    self.assertEquals("seqneg/bar.-1-1#.exr", str(seqs[0]))
AssertionError: 'seqneg/bar.-1-1#.exr' != 'seqneg\\bar.-1-1#.exr'

======================================================================
FAIL: testFindSequencesOnDisk (__main__.TestFindSequencesOnDisk)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run.py", line 1567, in testFindSequencesOnDisk
    self.assertFalse(known.difference(found))
AssertionError: set(['seq/foo.1-5#.exr', 'seq/bar1000-1002,1004-1006#.exr', 'seq/1-3#.exr', 'seq/foo.1-5#.jpg', 'seq/foo_1#.exr', 'seq/foo.debug.1-5#.exr']) is not false

======================================================================
FAIL: testFindSequencesOnDiskIncludeHiddenFiles (__main__.TestFindSequencesOnDisk)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run.py", line 1608, in testFindSequencesOnDiskIncludeHiddenFiles
    self.assertEqual(known, found)
AssertionError: Items in the first set but not the second:
'seqhidden/foo.1-5#.exr'
'seqhidden/foo.1-5#.jpg'
'seqhidden/.foo.1-5#.jpg'
'seqhidden/.hidden'
'seqhidden/.foo.1-5#.exr'
'seqhidden/.bar1000-1002,1004-1006#.exr'
'seqhidden/bar1000-1002,1004-1006#.exr'
Items in the second set but not the first:
'seqhidden\\.foo.1-5#.jpg'
'seqhidden\\bar1000-1002,1004-1006#.exr'
'seqhidden\\foo.1-5#.jpg'
'seqhidden\\foo.1-5#.exr'
'seqhidden\\.hidden'
'seqhidden\\.bar1000-1002,1004-1006#.exr'
'seqhidden\\.foo.1-5#.exr'

======================================================================
FAIL: testFindSequencesOnDiskSkipHiddenFiles (__main__.TestFindSequencesOnDisk)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "run.py", line 1591, in testFindSequencesOnDiskSkipHiddenFiles
    self.assertEqual(known, found)
AssertionError: Items in the first set but not the second:
'seqhidden/foo.1-5#.jpg'
'seqhidden/foo.1-5#.exr'
'seqhidden/bar1000-1002,1004-1006#.exr'
Items in the second set but not the first:
'seqhidden\\foo.1-5#.exr'
'seqhidden\\bar1000-1002,1004-1006#.exr'
'seqhidden\\foo.1-5#.jpg'

----------------------------------------------------------------------
Ran 48674 tests in 11.009s

FAILED (failures=6)
```

I will try to have a look and figure how to fix it but I cannot promise anything. The regex patch got the part we needed working for our production code.

**Comment by justinfx** [comment]
Yea, unfortunately I don't use windows so I had to work out a test that would mock the pathing logic using `ntpath`. But apparently I really need to run this on windows to assert it properly. My changes obviously impact the separator being used and it may just be a matter of updating the test cases some more. 

I also need to update the travis ci configuration file to make it also run the unit tests on windows.

**Comment by justinfx** [comment]
So the reason these are failing is simply because no one has seemed to have run the tests on Windows and the test paths always expect a forward slash. It may just be a matter of adapting the tests to be more platform agnostic when it compares the paths.

As for the way the tests currently are, because forward and back slashes are valid in Windows, @p0las as a windows user, do you find it reasonable to get back a sequence using back slashes even if the input path was using forward slashes?

**Comment by p0las** [comment]
windows slashes handling is a mess. 
I think it is ok to return platform-specific slashes regardless of the input ones. A lot of python libraries do that.
you have two choices:
preconvert all input slashes to forward ones and don't use os.path in your code. Or wrap the outputs into os.path.normpath to return platform-specific paths.
either way windows is messy but python is ok with either slashes and personally, I tend to use forward slashes in the code and stay away from os.path

**Comment by justinfx** [comment]
With the work I had committed to `42_windows_path_sep` it might just be enough to make sure the comparisons in the tests between the actual and expected values are wrapped in `os.path.normpath`

**Comment by p0las** [comment]
sounds like a reasonable solution. cheers.

**Comment by justinfx** [comment]
Added AppVeyor support so that CI runs on windows
