### ISSUE TITLE
Add FileSequence.getPaddingNum method

### ISSUE THREAD

**Issue by matthewkapfhammer** [sqlboy/fileseq#7]
Add a method to get the padding number back from padding characters.

**Comment by justinfx** [comment]
Did you have a pull request you were going to submit for this or should we close it? I don't remember the specifics of this issue because there is no description.

**Comment by matthewkapfhammer** [comment]
I need to pull the latest, add my proposed change and submit a new pull request. The previous one was too messy to review.

**Comment by matthewkapfhammer** [comment]
I got the changes in. I want to update the README.md before I submit a new merge request.

**Comment by matthewkapfhammer** [comment]
I separated out the README changes. The new merge request should be pretty clean. 

Cheers,
MK

**Comment by justinfx** [comment]
Merged
